#lang racket
(require spd-grader/grader)
(provide grader)


(define grader
  (lambda ()
    (grade-submission
      (grade-problem 1
        (grade-htdf solve
	  (let* ([htdf (car (context))]
		 [tests (htdf-checks htdf)])
            (weights (.02 .1 .03 .2 *)
              (grade-signature (Maze -> (listof Pos) or false))
              (rubric-item 'signature 1 (andmap (curryr member '(M1 M2 M3 M4 M5 M6 M7))
                                                (map cadr (map cadr tests)))
                           "Should have tests for all 7 of M1...M7")
              (grade-template-origin (genrec arb-tree try-catch accumulator))
              (grade-submitted-tests 1)
              (grade-additional-tests 1
                (check-expect (solve M1) (list (make-pos 0 0)
                                               (make-pos 0 1)
                                               (make-pos 1 1)
                                               (make-pos 1 2)
                                               (make-pos 1 3)
                                               (make-pos 1 4)
                                               (make-pos 2 4)
                                               (make-pos 3 4)
                                               (make-pos 4 4)))
                (check-expect (solve M2) (list (make-pos 0 0)
                                               (make-pos 1 0)
                                               (make-pos 2 0)
                                               (make-pos 3 0)
                                               (make-pos 4 0)
                                               (make-pos 4 1)
                                               (make-pos 4 2)
                                               (make-pos 4 3)
                                               (make-pos 4 4)))
                (check-expect (solve M3) (list (make-pos 0 0)
                                               (make-pos 0 1)
                                               (make-pos 0 2)
                                               (make-pos 0 3)
                                               (make-pos 0 4)
                                               (make-pos 1 4)
                                               (make-pos 2 4)
                                               (make-pos 3 4)
                                               (make-pos 4 4))) 
                (check-expect (solve M4) (list (make-pos 0 0)
                                               (make-pos 1 0)
                                               (make-pos 2 0)
                                               (make-pos 3 0)
                                               (make-pos 4 0)
                                               (make-pos 4 1)
                                               (make-pos 4 2)
                                               (make-pos 3 2)
                                               (make-pos 2 2)
                                               (make-pos 2 3)
                                               (make-pos 2 4)
                                               (make-pos 3 4)
                                               (make-pos 4 4)))
                (check-expect (solve M5) #f)
                (check-expect (solve M6) (list (make-pos 0 0)
                                               (make-pos 1 0)
                                               (make-pos 2 0)
                                               (make-pos 2 1)
                                               (make-pos 2 2)
                                               (make-pos 2 3)
                                               (make-pos 3 3)
                                               (make-pos 3 4)
                                               (make-pos 3 5)
                                               (make-pos 3 6)
                                               (make-pos 3 7)
                                               (make-pos 4 7)
                                               (make-pos 5 7)
                                               (make-pos 5 6)
                                               (make-pos 5 5)
                                               (make-pos 5 4)
                                               (make-pos 5 3)
                                               (make-pos 5 2)
                                               (make-pos 5 1)
                                               (make-pos 5 0)
                                               (make-pos 6 0)
                                               (make-pos 7 0)
                                               (make-pos 8 0)
                                               (make-pos 9 0)
                                               (make-pos 9 1)
                                               (make-pos 9 2)
                                               (make-pos 8 2)
                                               (make-pos 7 2)
                                               (make-pos 7 3)
                                               (make-pos 7 4)
                                               (make-pos 8 4)
                                               (make-pos 9 4)
                                               (make-pos 9 5)
                                               (make-pos 9 6)
                                               (make-pos 8 6)
                                               (make-pos 7 6)
                                               (make-pos 7 7)
                                               (make-pos 7 8)
                                               (make-pos 8 8)
                                               (make-pos 9 8)
                                               (make-pos 9 9)))
                (check-expect (solve M7) (list
                                          (make-pos 0 0)
                                          (make-pos 1 0)
                                          (make-pos 2 0)
                                          (make-pos 3 0)
                                          (make-pos 4 0)
                                          (make-pos 5 0)
                                          (make-pos 6 0)
                                          (make-pos 7 0)
                                          (make-pos 8 0)
                                          (make-pos 9 0)
                                          (make-pos 9 1)
                                          (make-pos 9 2)
                                          (make-pos 8 2)
                                          (make-pos 7 2)
                                          (make-pos 7 3)
                                          (make-pos 7 4)
                                          (make-pos 8 4)
                                          (make-pos 9 4)
                                          (make-pos 9 5)
                                          (make-pos 9 6)
                                          (make-pos 8 6)
                                          (make-pos 7 6)
                                          (make-pos 7 7)
                                          (make-pos 7 8)
                                          (make-pos 8 8)
                                          (make-pos 9 8)
                                          (make-pos 9 9)))))))))))
  
